version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      -run: sudo apt install wget
      -run: wget https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz
      -run: tar xzf cmake-3.11.0-Linux-x86_64.tar.gz
      -run: export PATH=`pwd`/cmake-3.11.0-Linux-x86_64/bin:$PATH
      -run: ndk_file=android-ndk-r16b-linux-x86_64.zip
      -run: wget "http://dl.google.com/android/repository/${ndk_file}"
      -run: unzip -oq ${ndk_file}
      -run: rm ${ndk_file}
      -run: export ANDROID_NDK=`pwd`/android-ndk-r16b

      -run: pwd
      -run: mkdir build_arm
      -run: cd build_arm;
      -run: cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_PLATFORM=android-17 ..
      -run: make

      -run: cd ..

      -run: mkdir build_arm64
      -run: cd build_arm64
      -run: cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-17 ..
      -run: make